### ISSUE TITLE
Error: Cannot write to file outside

### ISSUE THREAD

**Issue by xaeroborg** [chbrown/unmap#1]
When unmapping a source js.map file of size 6.7mb, an error comes out **Error: Cannot write to file outside /tmp: /node_modules/react/index.js** where /tmp is the output folder

**Comment by chbrown** [comment]
Hi, thanks for your report — I take it your source map file is using absolute paths and that `unmap` isn't resolving those properly? Seems like a bug or at least an unnecessary limitation. 

I've never run into that error myself, and it'd be helpful to be able to replicate it. Can you share the file (attach to comment / create gist and reply with link) or point me to where you found it (reply with URL)?

**Comment by xaeroborg** [comment]
> Hi, thanks for your report — I take it your source map file is using absolute paths and that `unmap` isn't resolving those properly? Seems like a bug or at least an unnecessary limitation.
> 
> I've never run into that error myself, and it'd be helpful to be able to replicate it. Can you share the file (attach to comment / create gist and reply with link) or point me to where you found it (reply with URL)?

Hi, thanks for your prompt response. Unfortunately the source map file belongs to a client that I am conducting security assessment on. Hence why I wouldnt be able to share it or provide you with the link. Is there any other way around this?

**Comment by chbrown** [comment]
Okay so re-reading through the codebase, turns out I deliberately decided to throw that error when the `source` or `sourceRoot` fields use an absolute path. Maybe not the best idea, but I probably had a good reason (maybe? 🤷‍♂️ ).

It's a kinda silly hack of a workaround, but try this:
```sh
unmap --output / --sourceRoot tmp your_weird_file.js.map
```

**Comment by xaeroborg** [comment]
> 
> 
> Okay so re-reading through the codebase, turns out I deliberately decided to throw that error when the `source` or `sourceRoot` fields use an absolute path. Maybe not the best idea, but I probably had a good reason (maybe? 🤷‍♂️ ).
> 
> It's a kinda silly hack of a workaround, but try this:
> 
> ```shell
> unmap --output / --sourceRoot tmp your_weird_file.js.map
> ```

Your trick did work on but not fully, it extracted majority of files yet got the same error `Error: Cannot write to file outside /home-path/: /home-path/packages/react-router/index.tsx`

**Comment by chbrown** [comment]
It sounds like you used `--output /home-path/` instead of `--output /` which is missing the point

Please show the _exact_ command you're using when you call `unmap`

**Comment by xaeroborg** [comment]
> 
> 
> It sounds like you used `--output /home-path/` instead of `--output /` which is missing the point
> 
> Please show the _exact_ command you're using when you call `unmap`

This is how I made it work after reading your workaround.
Trial 1: `unmap --output / --sourceRoot tmp clientfile.chunk.js.map` threw an error 
`Error: ENOENT: no such file or directory, mkdir`
 
Trial 2: `unmap --sourceRoot tmp clientfile.chunk.js.map 
Error: Cannot write to file outside /home-pathwhereclientfileislocated: /home-pathwhereclientfileislocated/packages/react-router/index.tsx`

Its only after Trial 2 I was able to see it extracted lot of files organized into folders etc., but I guess it couldnt unmap further while unmapping /packages/react-router/index.tsx

**Comment by chbrown** [comment]
I imagine you've moved on, but [v1.1.0](https://www.npmjs.com/package/unmap/v/1.1.0) (published just now! 🌟 ) _should_ resolve your issue.

Can't verify since I can't replicate your specific scenario without access to your original source map, but I'm guessing it has absolute paths in some of the `source` fields, which should be handled more resiliently by this change, by using `path.join` instead of `path.resolve`.
